
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-20T04:25:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a6457c1d0410abe3c14f1bd84a9d45090f79136",
 "version": "v1.1.0+16.g3a6457c"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
